# 모델 경로
MODEL_PATH: "models/모델가중치파일.pth"

# 토크나이저
TOKENIZER_NAME: "KETI-AIR/ke-t5-base"

# vocab / 토큰 인덱스들
LEN_VOCAB: 64101
START_IDX: 64100
END_IDX: 1
PADDING_IDX: 0
UNK_IDX: 2

# 모델 차원
Q_DIM: 512

# weight tying 방식 (Enum 이름과 일치해야 함)
WEIGHT_TYING: "NOTYING"      # NOTYING, TYINGALL, TYINGSRCTGT, TYINGTGTFFC, TYINGSRCFFC 중 하나

# 시각화 옵션
VISUALIZATION: true          # true / false
HTML_PATH: "html_viz"
HTML_PATH_ABS: "html_viz 폴더 절대경로 입력"

# 인퍼런스 관련
MAX_LENGTH: 512
BATCH_SIZE: 1

# 유저 인증 관련
SECRET_KEY: "openssl rand -base64 64 등의 명령어로 생성해서 입력" 
ALGORITHM: "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES: 30